# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a797ef742ddd8356e4d91a73092c75d92a73b731890f706525aaf9ff409283bdfa6479ffe83d7ea044ea4b1aa6c259a6d8f5f905f45c56e14ac78b5e9801605

test:
  secret_key_base: 34855f7e0a443c019ff73241b592bd9ea39e1aa3d63ef1fb3e2629cb386fec6b591ddf4fdb10a1a8567f6ed20be585f7f210b58ca8cbdf217f852260c6d98a67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
